config/routes.rb
McitWaiver::Application.routes.draw do
  get "admin" => "admin#home"

  devise_for :admins

  devise_for :users, :controllers => {:registrations => "registrations"}

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'users/:id' => 'users#show', as: :user
 
  resources :users

  resources :courses

  resources :waivers

  get "home/index"

  get "confirm" => "waivers#confirm"

  root :to => 'home#index'

  get "data" => "waivers#data"

  resources :waivers do
    member do
      post 'deny'
    end
  end

  resources :waivers do
    member do
      post 'approve'
    end
  end

  resources :courses do
    member do
      post 'subscribe'
    end
  end

  resources :courses do
    member do
      post 'unsubscribe'
    end
  end

end

app/views/admin/home.html.erb
<div class="container">


<h1 class="jumbotron">Administrator Dashboard</h1>

</div>

<div class="container text-center">
	<div class="row">

		<div class="col-md-3">
			<ul class="list-unstyled">
				<li>
					<%= link_to "Edit Instructors", users_path, :class => "btn btn-lg btn-default btn-block"  %> 
				</li>
			</ul>
		</div>

		<div class="col-md-3">
			<ul class="list-unstyled">
				<li>
					<%= link_to "Edit Courses", courses_path, :class => "btn btn-lg btn-default btn-block"  %>
				</li>
			</ul>
		</div>

		<div class="col-md-3">
			<ul class="list-unstyled">
				<li>
					<%= link_to "Waivers", waivers_path, :class => "btn btn-lg btn-default btn-block"  %> 
				</li>
			</ul>
		</div>

		<div class="col-md-3">
			<ul class="list-unstyled">
				<li>
					<%= link_to "Data", data_path, :class => "btn btn-lg btn-default btn-block"  %>
				</li>
			</ul>
		</div>

	</div>


	<br>
	<%= link_to('Logout', destroy_admin_session_path, method: :delete, :class => "btn btn-lg btn-default " ) %>

</div>