config/routes.rb
McitWaiver::Application.routes.draw do
  get "admin" => "admin#home"

  devise_for :admins

  devise_for :users, :controllers => {:registrations => "registrations"}

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'users/:id' => 'users#show', as: :user
 
  resources :users

  resources :courses

  resources :waivers

  get "home/index"

  get "confirm" => "waivers#confirm"

  root :to => 'home#index'

  get "data" => "waivers#data"

  resources :waivers do
    member do
      post 'deny'
    end
  end

  resources :waivers do
    member do
      post 'approve'
    end
  end

  resources :courses do
    member do
      post 'subscribe'
    end
  end

  resources :courses do
    member do
      post 'unsubscribe'
    end
  end

end

app/models/waiver.rb
# == Schema Information
#
# Table name: waivers
#
#  id                       :integer          not null, primary key
#  first_name               :string(255)
#  last_name                :string(255)
#  waiver_class             :string(255)
#  replacement_class        :string(255)
#  taken_replacement_class  :string(255)
#  comments                 :text
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  email                    :string(255)
#  status                   :string(255)
#  course_id                :integer
#  timestamp                :datetime
#  documentation            :string(255)
#  course_taken_website     :string(255)
#  instructor_comments      :string(255)
#  transcript               :string(255)
#  additional_documentation :string(255)
#

class Waiver < ActiveRecord::Base
  belongs_to :course
  attr_accessible :comments, :first_name, :last_name, :email, :replacement_class, 
    :taken_replacement_class, :waiver_class, :status, :course_id, :course, 
    :documentation, :course_taken_website, :instructor_comments, 
    :additional_documentation, :transcript
  mount_uploader :documentation, DocumentationUploader
  mount_uploader :additional_documentation, AdditionalDocumentationUploader
  mount_uploader :transcript, TranscriptUploader
  
  before_save :default_values
  def default_values
    self.status ||= 'Pending'
  end

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.upenn.edu\Z/i

  validates_presence_of :first_name, :last_name, :email, :replacement_class, :taken_replacement_class, :course_id
  validates_uniqueness_of :email
  validates_length_of :first_name, :maximum => 50
  validates_length_of :last_name, :maximum => 50
  validates_length_of :email, :maximum => 100
  validates_length_of :replacement_class, :maximum => 255
  validates_length_of :comments, :maximum => 2000
  validates_format_of :email, :with => EMAIL_REGEX, :message =>"must be a Penn email address."
  validates_confirmation_of :email

#  searchable do
 #   text :comments, :instructor_comments, :first_name, :last_name, :email, :replacement_class, :taken_replacement_class, :waiver_class, :status, :course
  #end
end

app/controllers/waivers_controller.rb
# == Schema Information
#
# Table name: waivers
#
#  id                       :integer          not null, primary key
#  first_name               :string(255)
#  last_name                :string(255)
#  waiver_class             :string(255)
#  replacement_class        :string(255)
#  taken_replacement_class  :string(255)
#  comments                 :text
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  email                    :string(255)
#  status                   :string(255)
#  course_id                :integer
#  timestamp                :datetime
#  documentation            :string(255)
#  course_taken_website     :string(255)
#  instructor_comments      :string(255)
#  transcript               :string(255)
#  additional_documentation :string(255)
#

class WaiversController < ApplicationController

# checks that admin is logged in
before_filter :check_admin_logged_in!, except: [:confirm, :new, :create,
  :show, :approve, :deny, :update_attribute, :update]

# checks that instructor is logged in
before_filter :check_user_logged_in!, only: [:show, :approve, :deny, :update_attribute, :update]

  # GET /waivers
  # GET /waivers.json

  helper_method :sort_column, :sort_direction

  def index
    @waivers = Waiver.order(sort_column + " " + sort_direction)

    if params[:search].present?
      @search = Waiver.search do
        fulltext params[:search]
      end
      @waivers = @search.results
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @waivers }
    end
  end

  # GET /waivers/1
  # GET /waivers/1.json
  def show
    @waiver = Waiver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @waiver }
    end
  end

  # GET /waivers/new
  # GET /waivers/new.json
  def new
    @waiver = Waiver.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @waiver }
    end
  end

  # GET /waivers/1/edit
  def edit
    @waiver = Waiver.find(params[:id])
  end

  # POST /waivers
  # POST /waivers.json
  def create
    @waiver = Waiver.new(params[:waiver])

    respond_to do |format|
      if @waiver.save
        format.html { redirect_to confirm_path(:id => @waiver.id), notice: 'Waiver was successfully created.' }
        format.json { render json: @waiver, status: :created, location: @waiver }
      else
        format.html { render action: "new" }
        format.json { render json: @waiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /waivers/1
  # PUT /waivers/1.json
  def update
    @waiver = Waiver.find(params[:id])

    respond_to do |format|
      if @waiver.update_attributes(params[:waiver])
        format.html { redirect_to @waiver, notice: 'Waiver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @waiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waivers/1
  # DELETE /waivers/1.json
  def destroy
    @waiver = Waiver.find(params[:id])
    @waiver.destroy

    respond_to do |format|
      format.html { redirect_to waivers_url }
      format.json { head :no_content }
    end
  end

  def deny
    @waiver = Waiver.find(params[:id])
    @waiver.update_attribute(:status, "Denied")
    WaiverMailer.waiver_denied_email(@waiver).deliver    
    redirect_to @waiver
  end

  def approve
    @waiver = Waiver.find(params[:id])
    @waiver.update_attribute(:status, "Approved")
    WaiverMailer.waiver_approved_email(@waiver).deliver 
    redirect_to @waiver
  end

  def confirm
    @waiver = Waiver.find(params[:id])
    WaiverMailer.confirmation_email(@waiver).deliver
    if @waiver.course.email_opt_in
      WaiverMailer.instructor_notification_email(@waiver).deliver
    end
  end

  def data
    @waivers = Waiver.all
    @courses = Course.all
  end
  

  private
    def sort_column
      Waiver.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
  
    def check_admin_logged_in! # admin must be logged in
        authenticate_admin!
    end

    def check_user_logged_in! # if admin is not logged in, instructor must be logged in
      if !admin_signed_in?
        authenticate_user!
      end   
    end
end

app/helpers/waivers_helper.rb
# == Schema Information
#
# Table name: waivers
#
#  id                       :integer          not null, primary key
#  first_name               :string(255)
#  last_name                :string(255)
#  waiver_class             :string(255)
#  replacement_class        :string(255)
#  taken_replacement_class  :string(255)
#  comments                 :text
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  email                    :string(255)
#  status                   :string(255)
#  course_id                :integer
#  timestamp                :datetime
#  documentation            :string(255)
#  course_taken_website     :string(255)
#  instructor_comments      :string(255)
#  transcript               :string(255)
#  additional_documentation :string(255)
#

module WaiversHelper
end

app/views/waivers/_form.html.erb
<div class="container">
  <div class="form-group">

    <%= form_for @waiver, :html => {:multipart => true} do |f| %>
      <div class = "row">
        <div class="col-md-offset-3 col-md-6">
        <% if @waiver.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@waiver.errors.count, "error") %> prohibited this waiver from being saved:</h2>

            <ul>
            <% @waiver.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field form-control">
          <%= f.text_field :first_name, placeholder: "First Name"%>
        </div>
        <div class="field form-control">
          <%= f.text_field :last_name, placeholder: "Last Name" %>
        </div>
        <div class="field form-control">
          <%= f.text_field :email, placeholder: "Email Address" %>
        </div>
        <div class="field">
          <%= f.label :course %><br />
          <%= collection_select(:waiver, :course_id, Course.all, :id, :name) %><br />
        </div> 
        <div class="field form-control">
          <%= f.text_field :replacement_class, placeholder: "Replacement Class"%>
        </div>

        <div class="field">
          <label><b>Taken Replacement Class: </b></label>
          <%= f.select :taken_replacement_class, ['Yes','No'] %><br /> 
        </div>  
        <div class="field form-control">
          <%= f.text_field :course_taken_website, placeholder: "Course Taken Website" %>
        </div>
      </div>
    </div>

    <div class="row upload">
      <div class="col-md-offset-3 col-md-2">
        <div class="field">
          
          <span class="btn btn-default btn-file btn-block">
            
            
            <%= f.file_field :documentation, placeholder: "Upload Syllabus PDF"  %> 
            <b>Syllabus</b> (PDFs only)
            <br>
          </span>
        </div>
      </div>

      <div class="col-md-2">
        <div class="field">
          
          <span class="btn btn-default btn-file btn-block">
            <%= f.file_field :transcript, placeholder: "Upload Transcript PDF" %>
            <b>Transcript</b> (PDFs only) 
            <br>
          </span>
        </div> 
      </div> 

      <div class="col-md-2">
        <div class="field">
          
            <span class="btn btn-default btn-file btn-block">
              <%= f.file_field :additional_documentation, placeholder: "Upload Additional File" %>
              <b>Additional File</b>
              <br>
            </span>
        </div>
      </div>
    </div> 

      <div class="row">
        <div class="col-md-offset-3 col-md-6">
          <div class="field">
            <%= f.text_area :comments,  placeholder: "Comments", :class => "form-control", :rows => "6"   %>
          </div> 
        </div> 
      </div>

      

  <div class="row">
    <div class="col-md-offset-3 col-md-3">
        <div class="actions">
          <%= f.submit "Submit", class: "btn btn-lg btn-default btn-block" %>
        </div>
    </div>

    <div class="col-md-3">
      <% if admin_signed_in?%>
          <div class="actions">
              <%= link_to 'Back', waivers_path, :class => "btn btn-lg btn-default btn-block" %>
          </div>
        <% else %>
          <div class="actions">
              <%= link_to 'Back', root_path, :class => "btn btn-lg btn-default btn-block" %>
          </div>
        <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/waivers/confirm.html.erb
<h1>Waiver confirmation</h1>

<p>Waiver was successfully submitted!</p>

<p>You should receive a confirmation email soon.</p>

<p><%= link_to 'Back to home', root_path %> </p>

app/views/waivers/data.html.erb
<h1>Waiver Data</h1>
<div class="table-responsive">
<table class="table table-striped">
  <tr>
    <th>Total number of waivers</th>
    <th>Total number of approved waivers</th>
    <th>Total number of denied waivers</th>
    <th>Waivers by Semester</th>
    <th>Waivers by Course</th>
  </tr>

  <tr>
    <td><%= @waivers.length %></td>
    <td><%= @waivers.select{|waiver| waiver.status == "Approved"}.length %></td>
    <td><%= @waivers.select{|waiver| waiver.status == "Denied"}.length %></td>
    <td>  
      <% year = 0 %>      
      <% @waivers.each do |waiver_to_get_year| %>
        <% @fall_waivers = 0 %>
        <% @spring_waivers = 0 %>
        <% @waivers.each do |waiver| 
          if waiver.created_at.month > 7 
            @fall_waivers = @fall_waivers + 1
          else 
            @spring_waivers = @spring_waivers + 1
          end %>
        <% end %>
        <% if year != waiver_to_get_year.created_at.year %>
          Fall <%= waiver_to_get_year.created_at.year %> waivers = <%= @fall_waivers %></br>
          Spring <%= waiver_to_get_year.created_at.year %> waivers = <%= @spring_waivers %></br>
          <% year = waiver_to_get_year.created_at.year %>
        <% end %>
     <% end %>
    </td>

    <td>
      <% @courses.each do |course| %>
        <%= course.name %> = <%=  course.waivers.length %></br>
      <% end %>
    </td>
  </tr>
</table>

</div>


<%= link_to('Admin Logout', destroy_admin_session_path, method: :delete, :class => "btn btn-lg btn-default") %> 
<%= link_to "Administrator Dashboard", admin_path, :class => "btn btn-lg btn-default" %>

app/views/waivers/edit.html.erb
<h1>Editing waiver</h1>

<%= render 'form' %>

<%= link_to 'Show', @waiver %> |
<% if admin_signed_in?%>
  <%= link_to 'Back', waivers_path %>
<% elsif user_signed_in? %>
  <%= link_to 'Back', course_path(@waiver.course_id) %>
<% end %>

app/views/waivers/index.html.erb
<div class="container">

    <h1>All Waivers</h1>
    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
      <tr>
        <th></th>
        <th><%= sortable "created_at", "Timestamp" %></th>
        <th><%= sortable "first_name" %></th>
        <th><%= sortable "last_name" %></th>
        <th><%= sortable "email" %></th>
        <th><%= sortable "waiver_class" %></th>
        <th><%= sortable "replacement_class" %></th>
        <th><%= sortable "taken_replacement_class" %></th>
        <th><%= sortable "comments" %></th>
        <th><%= sortable "status" %></th>
        <th><%= sortable "documentation", "Syllabus" %></th>
        <th><%= sortable "transcript", "Transcript" %></th>
        <th><%= sortable "additional_documentation", "Additional Documentation" %></th>
        
      </tr>
    </thead>

    <% @waivers.each do |waiver| %>
      <tr>
        <td><%= link_to 'Deny', deny_waiver_path(waiver), method: :post %><br /><%= link_to 'Approve', approve_waiver_path(waiver), method: :post %><br /><%= link_to 'Details', waiver %></td>
        <td><%= waiver.created_at %></td>
        <td><%= waiver.first_name %></td>
        <td><%= waiver.last_name %></td>
        <td><%= waiver.email %></td>
        <td><%= waiver.course.name %></td>
        <td><%= waiver.replacement_class %></td>
        <td><%= waiver.taken_replacement_class %></td>
        <td><%= waiver.comments %></td>
        <td><%= waiver.status %></td>
        <td><%= link_to 'Syllabus', waiver.documentation.url %></td>
        <td><%= link_to 'Transcript', waiver.transcript.url %></td>
        <td><%= link_to 'Additional Documentation', waiver.additional_documentation.url %></td>
        
      </tr>
    <% end %>
    </table>
    </div>

    <br />

    <div class="row">
        <div class="col-md-4">
            <%= link_to 'New Waiver', new_waiver_path, class: "btn btn-lg btn-default btn-block" %>
        </div>



        <% if admin_signed_in? %>
        <div class="col-md-4">
            <%= link_to('Logout', destroy_admin_session_path, method: :delete, class: "btn btn-lg btn-default btn-block") %>
        </div>
        <div class="col-md-4">
            <%= link_to "Dashboard", admin_path, class: "btn btn-lg btn-default btn-block" %>
        </div>
        <% end %>

        <% if user_signed_in? %>
        <div class="col-md-4">
            <%= link_to('Instructor Logout', destroy_user_session_path, method: :delete, class: "btn btn-lg btn-default btn-block") %>
        </div>
        <% end %>
    </div>
</div>

app/views/waivers/new.html.erb
<br/>
<h1>New Waiver Application</h1>
<br/>

<%= render 'form' %>

app/views/waivers/show.html.erb
<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <div id="waivers-show">

      <p id="notice"><%= notice %></p>
            <h2><%= @waiver.first_name %> <%= @waiver.last_name %></h2>
      <h4><%= @waiver.email %></h4>

      <% if @waiver.status == "Denied" %>
      <dl class="dl-horizontal bg-danger">
        <dt>Status:</dt>
          <dd><%= @waiver.status %></dd>
      </dl>
      <% end %>

      <% if @waiver.status == "Approved" %>
      <dl class="dl-horizontal bg-success">
        <dt>Status:</dt>
          <dd><%= @waiver.status %></dd>
      </dl>
      <% end %>

      <% if @waiver.status == "Pending" %>
      <dl class="dl-horizontal bg-warning">
        <dt>Status:</dt>
          <dd><%= @waiver.status %></dd>
      </dl>
      <% end %>
      
      <dl class="dl-horizontal">
        <dt>Submitted:</dt>
        <dd><%= @waiver.created_at %></dd>
      </dl>

      <dl class="dl-horizontal">
        <dt>Waive Course:</dt>
        <dd><%= @waiver.course.name %></dd>
      </dl>

      <dl class="dl-horizontal">
        <dt>Replacement Course:</dt>
        <dd><%= @waiver.replacement_class %></dd>
        <dd><%= @waiver.course_taken_website %></dd>
        <dt>Already Taken?</dt>
        <dd><%= @waiver.taken_replacement_class %></dd>
      </dl>

      <dl class="dl-horizontal">
        <dt>Comments:</dt>
        <dd><%= @waiver.comments %></dd>
        <dt>Attachments:</dt>
        <dd><%= @waiver.documentation.identifier %></dd>
        <dd><%= @waiver.transcript.identifier %></dd>
        <dd><%= @waiver.additional_documentation.identifier %></dd>
      </dl>
      
      <% if admin_signed_in?%>
        <%= link_to 'Edit', edit_waiver_path(@waiver), class: "btn btn-lg btn-default center-block"  %>
        <br />
        <%= link_to 'Back', waivers_path, class: "btn btn-lg btn-default center-block"  %>

      <% elsif user_signed_in? %>
        <%= link_to 'Back', course_path(@waiver.course_id), class: "btn btn-lg btn-default center-block"  %>
      <% end %>

    </div>

  </div>

</div>