config/routes.rb
McitWaiver::Application.routes.draw do
  get "admin" => "admin#home"

  devise_for :admins

  devise_for :users, :controllers => {:registrations => "registrations"}

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'users/:id' => 'users#show', as: :user
 
  resources :users

  resources :courses

  resources :waivers

  get "home/index"

  get "confirm" => "waivers#confirm"

  root :to => 'home#index'

  get "data" => "waivers#data"

  resources :waivers do
    member do
      post 'deny'
    end
  end

  resources :waivers do
    member do
      post 'approve'
    end
  end

  resources :courses do
    member do
      post 'subscribe'
    end
  end

  resources :courses do
    member do
      post 'unsubscribe'
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  has_many :courses
  has_many :waivers, through: :courses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.upenn.edu\Z/i
  validates_presence_of :email, :password
  validates_confirmation_of :email, :password
  validates_format_of :email, :with => EMAIL_REGEX, :message =>"must be a Penn email address."
  validates_length_of :email, :maximum => 100
  validates_length_of :password, :minimum => 8
  validates_uniqueness_of :email
  validates_confirmation_of :email

end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_to admin_path, notice: "Instructor removed."
    end
  end

end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

module UsersHelper
end

app/views/users/index.html.erb
<div class="container">

  <h1>Instructors</h1>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Instructor</th>
          <th>Options</th>
          <th></th>
        </tr>
      </thead>

      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= link_to "Delete", admin_destroy_user_path(user), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <% if user_signed_in? %>
  <%= link_to('Instructor Logout', destroy_user_session_path, method: :delete) %>
  <% end %>
  <br />


  <% if admin_signed_in? %>

    <div class="row">
      <div class="col-md-4">
        <%= link_to 'Add Instructor', new_user_registration_path, class: "btn btn-lg btn-default btn-block"  %>
      </div>
      <div class="col-md-4">
        <%= link_to('Logout', destroy_admin_session_path, method: :delete, class: "btn btn-lg btn-default btn-block") %>
      </div>
      <div class="col-md-4">
        <%= link_to "Dashboard", admin_path, class: "btn btn-lg btn-default btn-block" %>
      </div>
    </div>


  <% end %>

</div>